//3
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const ERROR_DOCTORS = "ERROR_DOCTORS";
export const LOADING_DOCTORS = "LOADING_DOCTORS";
export const GET_DOCTORS = "GET_DOCTORS";
export const ADD_DOCTORS = "ADD_DOCTORS";
export const UPDATE_DOCTORS = "UPDATE_DOCTORS";
export const DELETE_DOCTORS = "DELETE_DOCTORS";

export const GET_MEDICINE = "GET_MEDICINE";
export const ADD_MEDICINE = "ADD_DOCTORS";
export const DELETE_MEDICINE = "DELETE_DOCTORS";
export const UPDATE_MEDICINE = "UPDATE_DOCTORS";

export const ADD_TO_CARD = "ADD_TO_CARD";
export const ICN_CARD = "ICN_CARD";
export const DEN_CARD = "DEN_CARD";
export const REMOVE_CARD = "REMOVE_CART";

export const ADD_FEVORITE ="ADD_FEVORITE";
export const REMOVE_FEVORITE ="REMOVE_FEVORITE";

export const ADD_DESC = "ADD_DESC";
export const GET_DESC = "ADD_DESC";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGGED_IN = "LOGGED_IN";
export const FORGOT_REQUEST = "FORGOT_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGGED_OUT = "LOGGED_OUT";
export const AUTH_ERROR = "AUTH_ERROR";
